#!/usr/bin/perl -w -- 
#
# generated by wxGlade 0.6.8 (standalone edition) on Tue Apr 08 22:17:48 2014
#
# To get wxPerl visit http://wxPerl.sourceforge.net/
#

use Wx 0.15 qw[:allclasses];
use strict;

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

package MyFrame;

use Wx qw[:everything];
use base qw(Wx::Frame);
use strict;

use Wx::Locale gettext => '_T';
sub new {
    my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
    $parent = undef              unless defined $parent;
    $id     = -1                 unless defined $id;
    $title  = ""                 unless defined $title;
    $pos    = wxDefaultPosition  unless defined $pos;
    $size   = wxDefaultSize      unless defined $size;
    $name   = ""                 unless defined $name;

    # begin wxGlade: MyFrame::new
    $style = wxDEFAULT_FRAME_STYLE 
        unless defined $style;

    $self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
    

    # Menu Bar

    $self->{frame_1_menubar} = Wx::MenuBar->new();
    my $wxglade_tmp_menu;
    $wxglade_tmp_menu = Wx::Menu->new();
    $wxglade_tmp_menu->Append(wxID_ANY, _T("New"), "");
    $wxglade_tmp_menu->AppendSeparator();
    $wxglade_tmp_menu->Append(wxID_ANY, _T("Exit"), "");
    $self->{_T("frame_1_menubar")}->Append($wxglade_tmp_menu, _T("File"));
    $self->SetMenuBar($self->{frame_1_menubar});
    
# Menu Bar end

    $self->{frame_1_statusbar} = $self->CreateStatusBar(1, 0);

    $self->__set_properties();
    $self->__do_layout();

    # end wxGlade
    return $self;

}


sub __set_properties {
    my $self = shift;
    # begin wxGlade: MyFrame::__set_properties
    $self->SetTitle(_T("Spreadsheet to TBX-Min Converter"));
    $self->SetSize(Wx::Size->new(649, 470));
    $self->{frame_1_statusbar}->SetStatusWidths(-1);

	my( @frame_1_statusbar_fields ) = (
		_T("Open File/New to begin!")
	);

    if( @frame_1_statusbar_fields ) {
    	$self->{frame_1_statusbar}->SetStatusText($frame_1_statusbar_fields[$_], $_)
		for 0 .. $#frame_1_statusbar_fields ;
	}
    # end wxGlade
}

sub __do_layout {
    my $self = shift;
    # begin wxGlade: MyFrame::__do_layout
    $self->{sizer_1} = Wx::BoxSizer->new(wxVERTICAL);
    $self->SetSizer($self->{sizer_1});
    $self->Layout();
    # end wxGlade
}

# end of class MyFrame

1;

package MyNew;

use Wx qw[:everything];
use base qw(Wx::Dialog);
use strict;

use Wx::Locale gettext => '_T';
sub new {
    my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
    $parent = undef              unless defined $parent;
    $id     = -1                 unless defined $id;
    $title  = ""                 unless defined $title;
    $pos    = wxDefaultPosition  unless defined $pos;
    $size   = wxDefaultSize      unless defined $size;
    $name   = ""                 unless defined $name;

    # begin wxGlade: MyNew::new
    $style = wxDEFAULT_DIALOG_STYLE 
        unless defined $style;

    $self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
    $self->{panel_1} = Wx::ScrolledWindow->new($self, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    $self->{panel_2} = Wx::Panel->new($self, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxDOUBLE_BORDER|wxTAB_TRAVERSAL);

    $self->__set_properties();
    $self->__do_layout();

    # end wxGlade
    return $self;

}


sub __set_properties {
    my $self = shift;
    # begin wxGlade: MyNew::__set_properties
    $self->SetTitle(_T("dialog_1"));
    $self->{panel_1}->SetScrollRate(10, 10);
    # end wxGlade
}

sub __do_layout {
    my $self = shift;
    # begin wxGlade: MyNew::__do_layout
    $self->{sizer_2} = Wx::BoxSizer->new(wxVERTICAL);
    $self->{sizer_2}->Add($self->{panel_1}, 3, wxEXPAND, 0);
    $self->{sizer_2}->Add($self->{panel_2}, 1, wxEXPAND, 0);
    $self->SetSizer($self->{sizer_2});
    $self->{sizer_2}->Fit($self);
    $self->Layout();
    # end wxGlade
}

# end of class MyNew

1;

1;

package main;

unless(caller){
    # my $local = Wx::Locale->new("English", "en", "en"); # replace with ??
    # $local->AddCatalog("app"); # replace with the appropriate catalog name

    local *Wx::App::OnInit = sub{1};
    my $app = Wx::App->new();
    Wx::InitAllImageHandlers();

    my $frame_1 = MyFrame->new();

    $app->SetTopWindow($frame_1);
    $frame_1->Show(1);
    $app->MainLoop();
}
